print("Mark")
print("December 20th 2022")
print("i am signing up for replit's 100 days of Pyhton challenge")
print("I will be sure to spend some time every day coding along, for a mininum of 10 minutes a day")
print("I'll be using Replit, an amazing online IDE so i can do this from my phone wherever i happen to be. No excuse for not coding from thw middle of a fieid!")
print("I am feeling excited already")